# Generated by Django 5.0 on 2023-12-11 19:06

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TezosUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=36)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_comment='Date and time when user first time connected.')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default=api.models.get_uuid_hash, max_length=32, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Ended'), (2, 'Abandoned')], default=0)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tezosuser')),
            ],
        ),
        migrations.CreateModel(
            name='TransferedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=36)),
                ('token_id', models.PositiveIntegerField()),
                ('amount', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gamesession')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tezosuser')),
            ],
        ),
    ]
