# Generated by Django 5.0 on 2023-12-11 19:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tezosuser',
            name='payload',
            field=models.CharField(default=api.models.get_payload_for_sign, max_length=128),
        ),
        migrations.AddField(
            model_name='tezosuser',
            name='signature',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tezosuser',
            name='success_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tezosuser',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
