# Generated by Django 5.0 on 2023-12-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tezosuser_payload_tezosuser_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tezosuser',
            name='address',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='tezosuser',
            name='signature',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
