# Generated by Django 5.0 on 2023-12-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tezosuser_address_alter_tezosuser_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='tezosuser',
            name='public_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
