# Generated by Django 5.0 on 2024-01-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gamesession_creation_time_rename_bossdrop_boss_drop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='seconds_on_pause',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Ended'), (2, 'Abandoned'), (3, 'Paused')], default=0),
        ),
    ]
