# Generated by Django 5.0 on 2024-01-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gamesession_seconds_on_pause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='pause_init_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
