# Generated by Django 5.0 on 2024-01-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_gamesession_pause_init_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='boss_killed',
            field=models.BooleanField(default=False),
        ),
    ]
