# Generated by Django 5.0 on 2024-03-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_drop_boss_killed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('target_progress', models.IntegerField(default=1)),
                ('reward_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.token')),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.IntegerField(default=0)),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tezosuser')),
            ],
        ),
    ]
