# Generated by Django 5.0 on 2024-03-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Kill boss'), (1, 'Play games')], default=0),
        ),
    ]
